import type { Person } from '@/types/family';

export const initialFamilyData: Person[] = [
  // First Generation (Great Grandparents)
  {
    id: 1,
    shortName: 'George',
    fullName: 'George William Smith',
    age: 92,
    gender: 'Male',
    status: 'deceased',
    phone: '+1 234-567-8901',
    address: '123 Main St, Springfield, IL',
    parents: [],
    spouses: [{ id: 2, status: 'deceased' }],
    children: [
      { id: 3, type: 'biological' },
      { id: 4, type: 'biological' },
    ],
  },
  {
    id: 2,
    shortName: 'Beth',
    fullName: 'Elizabeth Anne Smith',
    age: 88,
    gender: 'Female',
    status: 'deceased',
    phone: '+1 234-567-8902',
    address: '123 Main St, Springfield, IL',
    parents: [],
    spouses: [{ id: 1, status: 'deceased' }],
    children: [
      { id: 3, type: 'biological' },
      { id: 4, type: 'biological' },
    ],
  },

  // Second Generation (Grandparents)
  {
    id: 3,
    shortName: 'Bob',
    fullName: 'Robert George Smith',
    age: 65,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8903',
    address: '456 Oak Ave, Springfield, IL',
    parents: [
      { id: 1, type: 'biological' },
      { id: 2, type: 'biological' },
    ],
    spouses: [{ id: 5, status: 'current' }],
    children: [
      { id: 7, type: 'biological' },
      { id: 8, type: 'biological' },
    ],
  },
  {
    id: 4,
    shortName: 'Maggie',
    fullName: 'Margaret Elizabeth Wilson',
    age: 62,
    gender: 'Female',
    status: 'alive',
    phone: '+1 234-567-8904',
    address: '789 Pine Rd, Springfield, IL',
    parents: [
      { id: 1, type: 'biological' },
      { id: 2, type: 'biological' },
    ],
    spouses: [
      { id: 6, status: 'divorced' },
      { id: 16, status: 'current' },
    ],
    children: [
      { id: 9, type: 'biological' },
      { id: 10, type: 'adoptive' },
    ],
  },
  {
    id: 5,
    shortName: 'Pat',
    fullName: 'Patricia Marie Brown',
    age: 63,
    gender: 'Female',
    status: 'alive',
    phone: '+1 234-567-8905',
    address: '456 Oak Ave, Springfield, IL',
    parents: [],
    spouses: [{ id: 3, status: 'current' }],
    children: [
      { id: 7, type: 'biological' },
      { id: 8, type: 'biological' },
    ],
  },
  {
    id: 6,
    shortName: 'Jim',
    fullName: 'James Edward Wilson',
    age: 64,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8906',
    address: '321 Elm St, Springfield, IL',
    parents: [],
    spouses: [{ id: 4, status: 'divorced' }],
    children: [
      { id: 9, type: 'biological' },
      { id: 10, type: 'adoptive' },
    ],
  },

  // Third Generation (Parents)
  {
    id: 7,
    shortName: 'Mike',
    fullName: 'Michael Robert Smith',
    age: 40,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8907',
    address: '567 Maple Dr, Springfield, IL',
    parents: [
      { id: 3, type: 'biological' },
      { id: 5, type: 'biological' },
    ],
    spouses: [{ id: 11, status: 'current' }],
    children: [
      { id: 13, type: 'biological' },
      { id: 14, type: 'biological' },
    ],
  },
  {
    id: 8,
    shortName: 'Jen',
    fullName: 'Jennifer Patricia Smith',
    age: 38,
    gender: 'Female',
    status: 'alive',
    phone: '+1 234-567-8908',
    address: '890 Cedar Ln, Springfield, IL',
    parents: [
      { id: 3, type: 'biological' },
      { id: 5, type: 'biological' },
    ],
    spouses: [{ id: 12, status: 'deceased' }],
    children: [{ id: 15, type: 'biological' }],
  },
  {
    id: 9,
    shortName: 'Dave',
    fullName: 'David James Wilson',
    age: 35,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8909',
    address: '234 Birch St, Springfield, IL',
    parents: [
      { id: 4, type: 'biological' },
      { id: 6, type: 'biological' },
    ],
    spouses: [],
    children: [],
  },
  {
    id: 10,
    shortName: 'Em',
    fullName: 'Emily Margaret Wilson',
    age: 32,
    gender: 'Female',
    status: 'alive',
    phone: '+1 234-567-8910',
    address: '567 Walnut Ave, Springfield, IL',
    parents: [
      { id: 4, type: 'adoptive' },
      { id: 6, type: 'adoptive' },
    ],
    spouses: [],
    children: [],
  },

  // Fourth Generation (Children)
  {
    id: 13,
    shortName: 'Will',
    fullName: 'William Michael Smith',
    age: 15,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8913',
    address: '567 Maple Dr, Springfield, IL',
    parents: [
      { id: 7, type: 'biological' },
      { id: 11, type: 'biological' },
    ],
    spouses: [],
    children: [],
  },
  {
    id: 14,
    shortName: 'Sophie',
    fullName: 'Sophia Emma Smith',
    age: 12,
    gender: 'Female',
    status: 'alive',
    phone: '+1 234-567-8914',
    address: '567 Maple Dr, Springfield, IL',
    parents: [
      { id: 7, type: 'biological' },
      { id: 11, type: 'biological' },
    ],
    spouses: [],
    children: [],
  },
  {
    id: 15,
    shortName: 'Ollie',
    fullName: 'Oliver Daniel Smith',
    age: 10,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8915',
    address: '890 Cedar Ln, Springfield, IL',
    parents: [
      { id: 8, type: 'biological' },
      { id: 12, type: 'biological' },
    ],
    spouses: [],
    children: [],
  },

  // Spouses of Third Generation
  {
    id: 11,
    shortName: 'Emma',
    fullName: 'Emma Grace Davis',
    age: 38,
    gender: 'Female',
    status: 'alive',
    phone: '+1 234-567-8911',
    address: '567 Maple Dr, Springfield, IL',
    parents: [],
    spouses: [{ id: 7, status: 'current' }],
    children: [
      { id: 13, type: 'biological' },
      { id: 14, type: 'biological' },
    ],
  },
  {
    id: 12,
    shortName: 'Dan',
    fullName: 'Daniel James Brown',
    age: 40,
    gender: 'Male',
    status: 'deceased',
    phone: '+1 234-567-8912',
    address: '890 Cedar Ln, Springfield, IL',
    parents: [],
    spouses: [{ id: 8, status: 'deceased' }],
    children: [{ id: 15, type: 'biological' }],
  },
  // New spouse for Margaret Wilson (id: 4)
  {
    id: 16,
    shortName: 'Tom',
    fullName: 'Thomas Richard Anderson',
    age: 60,
    gender: 'Male',
    status: 'alive',
    phone: '+1 234-567-8916',
    address: '789 Pine Rd, Springfield, IL',
    parents: [],
    spouses: [{ id: 4, status: 'current' }],
    children: [],
  },
] as const;
